name: "Setup UV Build Environment"
description: "Sets up the build environment with Python, dependencies, and tools."
runs:
  using: "composite"
  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        python-version: 3.11
        enable-cache: true
        cache-dependency-glob: |
          **/uv.lock
          **/pyproject.toml
        version: "latest"

    - name: Install dependencies
      run: |
        uv sync ${{ inputs.uv-args }}
      shell: bash
